<?xml version="1.0"?>
<robot name="101350" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find object_description)/chair_urdf/101350.SLDPRT.urdf"/>
	<xacro:include filename="$(find object_description)/xacro/for_assemble_macro.xacro"/>

	<xacro:property name="x_offset" value="0.0"/>
	<xacro:property name="y_offset" value="0.0"/>
	<xacro:property name="z_offset" value="0.0"/>

	<xacro:shaft_definition link_name="101350 pin insert 1" 
							length="0.03" 
							radius="0.004"
							x="${0.0 + x_offset}" y="${0.0 + y_offset}" z="${0.015 + z_offset}"
							rx="0" ry="0" rz="0"
							parent="101350.SLDPRT"/>

	<!--<xacro:shaft_definition link_name="101350 pin insert 2" 
							length="0.03" 
							radius="0.004"
							x="${0.0 + x_offset}" y="${0.0 + y_offset}" z="${0.015 + z_offset}"
							rx="${pi}" ry="0" rz="0"
							parent="101350.SLDPRT"/>-->
							
</robot>
