<?xml version="1.0"?>
<robot name="122925" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find object_description)/chair_urdf_for_real/122925.SLDPRT.urdf"/>
	<xacro:include filename="$(find object_description)/xacro_for_real/for_assemble_macro.xacro"/>

	<xacro:property name="x_offset" value="0.0"/>
	<xacro:property name="y_offset" value="0.0"/>
	<xacro:property name="z_offset" value="0.0"/>

	<xacro:shaft_definition link_name="122925 pin screw 1" 
							length="0.01" 
							radius="0.003"
							x="${0.0096 + x_offset}" y="${0.0 + y_offset}" z="${0.0 + z_offset}"
							rx="0" ry="${pi/2}" rz="0"
							parent="122925.SLDPRT"/>

</robot>
