<?xml version="1.0"?>
<robot name="part2" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find object_description)/chair_urdf/chair_part2.SLDPRT.urdf"/>
	<xacro:include filename="$(find object_description)/xacro/for_assemble_macro.xacro"/>

	<xacro:property name="x_offset" value="0.0"/>
	<xacro:property name="y_offset" value="0.0"/>
	<xacro:property name="z_offset" value="0.0"/>

	<xacro:hole_definition link_name="part2 hole blocked 1" 
						   length="0.02" 
						   radius="0.004"
						   x="${0.16 + x_offset}" y="${0.016 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${-pi/2}" rz="0"
						   parent="chair part2.SLDPRT"/>

	<xacro:hole_definition link_name="part2 hole blocked 2" 
						   length="0.02" 
						   radius="0.004"
						   x="${0.16 + x_offset}" y="${-0.016 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${-pi/2}" rz="0"
						   parent="chair part2.SLDPRT"/>

	<xacro:hole_definition link_name="part2 hole blocked 3" 
						   length="0.02" 
						   radius="0.004"
						   x="${-0.16 + x_offset}" y="${0.016 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${pi/2}" rz="0"
						   parent="chair part2.SLDPRT"/>

	<xacro:hole_definition link_name="part2 hole blocked 4" 
						   length="0.02" 
						   radius="0.004"
						   x="${-0.16 + x_offset}" y="${-0.016 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${pi/2}" rz="0"
						   parent="chair part2.SLDPRT"/>





	<xacro:hole_definition link_name="part2 hole blocked 5" 
						   length="0.013" 
						   radius="0.003"
						   x="${0.112 + x_offset}" y="${-0.0145 + y_offset}" z="${0.0135 + z_offset}"
						   rx="0" ry="${pi}" rz="0"
						   parent="chair part2.SLDPRT"/>

	<xacro:hole_definition link_name="part2 hole blocked 6" 
						   length="0.013" 
						   radius="0.003"
						   x="${-0.112 + x_offset}" y="${-0.0145 + y_offset}" z="${0.0135 + z_offset}"
						   rx="0" ry="${pi}" rz="0"
						   parent="chair part2.SLDPRT"/>



	<xacro:hole_definition link_name="part2 hole blocked 7" 
						   length="0.04" 
						   radius="0.0025"
						   x="${0.15 + x_offset}" y="${0.0 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${-pi/2}" rz="0"
						   parent="chair part2.SLDPRT"/>

	<xacro:hole_definition link_name="part2 hole blocked 8" 
						   length="0.04" 
						   radius="0.0025"
						   x="${-0.15 + x_offset}" y="${0.0 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${pi/2}" rz="0"
						   parent="chair part2.SLDPRT"/>


</robot>
