<?xml version="1.0"?>
<robot name="101350" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find object_description)/chair_urdf/101350.SLDPRT.urdf"/>
	<xacro:include filename="$(find object_description)/chair_xacro_re/for_assemble_macro.xacro"/>

	<xacro:property name="x_offset" value="0.0"/>
	<xacro:property name="y_offset" value="0.0"/>
	<xacro:property name="z_offset" value="0.0"/>

	<xacro:shaft_definition link_name="101350 shaft duplex part2-1-2-3-4/part3-1-2-3-4/part4-1-2-3-4-5-6/part5-1-2-3-4-5-6-7/part6-1-2-3-4-5-6-7 1" 
							length="0.03" 
							radius="0.004"
							x="${0.0 + x_offset}" y="${0.0 + y_offset}" z="${0.015 + z_offset}"
							rx="0" ry="0" rz="0"
							parent="101350.SLDPRT"/>

</robot>