<?xml version="1.0"?>
<robot name="104322" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find object_description)/chair_urdf/104322.SLDPRT.urdf"/>
	<xacro:include filename="$(find object_description)/chair_xacro_re/for_assemble_macro.xacro"/>

	<xacro:property name="x_offset" value="0.0"/>
	<xacro:property name="y_offset" value="0.0"/>
	<xacro:property name="z_offset" value="0.0"/>

	<xacro:shaft_definition link_name="104322 shaft simplex part5-8-9-10/part6-8-9-10 1" 
							length="0.06" 
							radius="0.003"
							x="${0.0 + x_offset}" y="${0.0 + y_offset}" z="${0.03 + z_offset}"
							rx="0" ry="0" rz="0"
							parent="104322.SLDPRT"/>


</robot>