<?xml version="1.0"?>
<robot name="part6" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find object_description)/chair_urdf/chair_part6.SLDPRT.urdf"/>
	<xacro:include filename="$(find object_description)/chair_xacro_re/for_assemble_macro.xacro"/>


	<xacro:property name="x_offset" value="0.0"/>
	<xacro:property name="y_offset" value="0.0"/>
	<xacro:property name="z_offset" value="0.015"/>


	<xacro:hole_definition link_name="part6 hole 101350-1 1" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.002166 + x_offset)}" y="${-(0.42666 + y_offset)}" z="${(0.01 + z_offset)}"
						   rx="0" ry="${-pi}" rz="0"
						   parent="chair part6.SLDPRT"/>

	<xacro:hole_definition link_name="part6 hole 101350-1 2" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.000492 + x_offset)}" y="${-(0.394704 + y_offset)}" z="${(0.01 + z_offset)}"
						   rx="0" ry="${-pi}" rz="0"
						   parent="chair part6.SLDPRT"/>						   

	<xacro:hole_definition link_name="part6 hole 101350-1 3" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.369042 + x_offset)}" y="${-(0.407433 + y_offset)}" z="${(0.045 + z_offset)}"
						   rx="0" ry="${-pi}" rz="0"
						   parent="chair part6.SLDPRT"/>
 
	<xacro:hole_definition link_name="part6 hole 101350-1 4" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.367368 + x_offset)}" y="${-(0.375477 + y_offset)}" z="${(0.045 + z_offset)}"
						   rx="0" ry="${-pi}" rz="0"
						   parent="chair part6.SLDPRT"/>

	<xacro:hole_definition link_name="part6 hole 101350-1 5" 
						   length="0.015" 
						   radius="0.004"
						   x="${(0.393244 + x_offset)}" y="${-(0.567391 + y_offset)}" z="${(0.0425 + z_offset)}"
						   rx="0" ry="${-pi}" rz="0"
						   parent="chair part6.SLDPRT"/>

	<xacro:hole_definition link_name="part6 hole 101350-1 6" 
						   length="0.015" 
						   radius="0.004"
						   x="${(0.427122 + x_offset)}" y="${-(0.844371 + y_offset)}" z="${(0.0425 + z_offset)}"
						   rx="0" ry="${-pi}" rz="0"
						   parent="chair part6.SLDPRT"/>

	<xacro:hole_definition link_name="part6 hole 101350-1 7" 
						   length="0.015" 
						   radius="0.004"
						   x="${(0.431575 + x_offset)}" y="${-(0.87606 + y_offset)}" z="${(0.0425 + z_offset)}"
						   rx="0" ry="${-pi}" rz="0"
						   parent="chair part6.SLDPRT"/>






	<xacro:hole_definition link_name="part6 hole 104322-1 8" 
						   length="0.03" 
						   radius="0.00275"
						   x="${(0.001329 + x_offset)}" y="${-(0.410682 + y_offset)}" z="${(0.0 + z_offset)}"
						   rx="0" ry="${0}" rz="0"
						   parent="chair part6.SLDPRT"/>

	<xacro:hole_definition link_name="part6 hole 104322-1 9"  
						   length="0.03" 
						   radius="0.00275"
						   x="${(0.368205 + x_offset)}" y="${-(0.391455 + y_offset)}" z="${(0.035 + z_offset)}"
						   rx="0" ry="${0}" rz="0"
						   parent="chair part6.SLDPRT"/>

	<xacro:hole_definition link_name="part6 hole 104322-1 10" 
						   length="0.03" 
						   radius="0.00275"
						   x="${(0.429349 + x_offset)}" y="${-(0.860216 + y_offset)}" z="${(0.035 + z_offset)}"
						   rx="0" ry="${0}" rz="0"
						   parent="chair part6.SLDPRT"/>




	<xacro:surface_definition link_name="part6 surface part1-4 1"
							  box_x="0.03" box_y="0.017" box_z="0.001"
							  x="${0.369534 + x_offset}" y="${-(0.852206/2 + y_offset)}" z="${0.05 + z_offset}"
							  rx="0" ry="0" rz="0"
							  parent="chair part6.SLDPRT"/>

	<xacro:surface_definition link_name="part6 surface part1-5 2"
							  box_x="0.32" box_y="0.02" box_z="0.001"
							  x="${0.369534/2 + x_offset}" y="${-(0.852206/2 + y_offset)}" z="${0.0175 + z_offset}"
							  rx="${pi/2}" ry="${(-90+84.115)*2*pi/360}" rz="${(3)*2*pi/360}"
							  parent="chair part6.SLDPRT"/>

	<xacro:surface_definition link_name="part6 surface part1-6 3"
							  box_x="0.03" box_y="0.017" box_z="0.001"
							  x="${0.354534 - 0.017794*cos(3/180*pi)*cos(87/180*pi) + x_offset}" y="${-(0.417206 + 0.017794*cos(3/180*pi)*cos(3/180*pi) + y_offset)}" z="${0.035 + z_offset}"
							  rx="0" ry="${-pi/2}" rz="${pi/180*3}"
							  parent="chair part6.SLDPRT"/>

</robot>