<?xml version="1.0"?>
<robot name="chair_part3_post" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find object_description)/chair_urdf/chair_part3.SLDPRT.urdf"/>
	<xacro:include filename="$(find object_description)/chair_xacro/for_assemble_macro.xacro"/>

	<xacro:property name="x_offset" value="0.0"/>
	<xacro:property name="y_offset" value="0.0"/>
	<xacro:property name="z_offset" value="0.0"/>

	<xacro:hole_definition link_name="hole_1" 
						   length="0.023" 
						   radius="0.004"
						   x="${0.1235 + x_offset}" y="${0.016 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${pi/2}" rz="0"
						   parent="chair part3.SLDPRT"/>


	<xacro:hole_definition link_name="hole_2" 
						   length="0.023" 
						   radius="0.004"
						   x="${0.1235 + x_offset}" y="${-0.016 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${pi/2}" rz="0"
						   parent="chair part3.SLDPRT"/>


	<xacro:hole_definition link_name="hole_3" 
						   length="0.023" 
						   radius="0.0025"
						   x="${0.1235 + x_offset}" y="${-0.0 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${pi/2}" rz="0"
						   parent="chair part3.SLDPRT"/>


	<xacro:hole_definition link_name="hole_4" 
						   length="0.023" 
						   radius="0.004"
						   x="${-0.1235 + x_offset}" y="${0.016 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${pi/2}" rz="0"
						   parent="chair part3.SLDPRT"/>


	<xacro:hole_definition link_name="hole_5" 
						   length="0.023" 
						   radius="0.004"
						   x="${-0.1235 + x_offset}" y="${-0.016 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${pi/2}" rz="0"
						   parent="chair part3.SLDPRT"/>


	<xacro:hole_definition link_name="hole_6" 
						   length="0.023" 
						   radius="0.0025"
						   x="${-0.1235 + x_offset}" y="${-0.0 + y_offset}" z="${0.01 + z_offset}"
						   rx="0" ry="${pi/2}" rz="0"
						   parent="chair part3.SLDPRT"/>	


	<xacro:hole_definition link_name="hole_7" 
						   length="0.013" 
						   radius="0.003"
						   x="${0.08 + x_offset}" y="${-0.0145 + y_offset}" z="${0.0135 + z_offset}"
						   rx="0" ry="0" rz="0"
						   parent="chair part3.SLDPRT"/>


	<xacro:hole_definition link_name="hole_8" 
						   length="0.013" 
						   radius="0.003"
						   x="${-0.08 + x_offset}" y="${-0.0145 + y_offset}" z="${0.0135 + z_offset}"
						   rx="0" ry="0" rz="0"
						   parent="chair part3.SLDPRT"/>


</robot>
