<?xml version="1.0"?>
<robot name="chair_part1_post" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find object_description)/chair_urdf/chair_part1.SLDPRT.urdf"/>
	<xacro:include filename="$(find object_description)/chair_xacro/for_assemble_macro.xacro"/>

	<xacro:property name="x_offset" value="0.0"/>
	<xacro:property name="y_offset" value="0.0"/>
	<xacro:property name="z_offset" value="0.0"/>


	<xacro:surface_definition link_name="surface_1"
							  box_x="0.037" box_y="0.001" box_z="0.01"
							  x="${0.1525 + x_offset}" y="${0.17 + y_offset}" z="${0.005 + z_offset}"
							  rx="0" ry="0" rz="0"
							  parent="chair part1.SLDPRT"/>


	<xacro:surface_definition link_name="surface_2"
							  box_x="0.037" box_y="0.001" box_z="0.01"
							  x="${-0.1525 + x_offset}" y="${0.17 + y_offset}" z="${0.005 + z_offset}"
							  rx="0" ry="0" rz="0"
							  parent="chair part1.SLDPRT"/>							  


	<xacro:surface_definition link_name="surface_3"
							  box_x="0.1" box_y="0.1" box_z="0.001"
							  x="${0 + x_offset}" y="${0 + y_offset}" z="${0 + z_offset}"
							  rx="0" ry="0" rz="0"
							  parent="chair part1.SLDPRT"/>	

</robot>