<?xml version="1.0"?>
<robot name="chair_part6_post" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find object_description)/chair_urdf/chair_part6.SLDPRT.urdf"/>
	<xacro:include filename="$(find object_description)/chair_xacro/for_assemble_macro.xacro"/>


	<xacro:property name="x_offset" value="0.0"/>
	<xacro:property name="y_offset" value="0.0"/>
	<xacro:property name="z_offset" value="0.015"/>


	<xacro:hole_definition link_name="hole_1" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.002166 + x_offset)}" y="${-(0.42666 + y_offset)}" z="${(0.01 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>


	<xacro:hole_definition link_name="hole_2" 
						   length="0.01" 
						   radius="0.00275"
						   x="${(0.001329 + x_offset)}" y="${-(0.410682 + y_offset)}" z="${(0.01 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>


	<xacro:hole_definition link_name="hole_3" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.000492 + x_offset)}" y="${-(0.394704 + y_offset)}" z="${(0.01 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>						   


	<xacro:hole_definition link_name="hole_4" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.369042 + x_offset)}" y="${-(0.407433 + y_offset)}" z="${(0.045 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>


	<xacro:hole_definition link_name="hole_5"  
						   length="0.01" 
						   radius="0.00275"
						   x="${(0.368205 + x_offset)}" y="${-(0.391455 + y_offset)}" z="${(0.045 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>

 
	<xacro:hole_definition link_name="hole_6" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.367368 + x_offset)}" y="${-(0.375477 + y_offset)}" z="${(0.045 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>


	<xacro:hole_definition link_name="hole_7" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.393244 + x_offset)}" y="${-(0.567391 + y_offset)}" z="${(0.045 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>


	<xacro:hole_definition link_name="hole_8" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.427122 + x_offset)}" y="${-(0.844371 + y_offset)}" z="${(0.045 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>


	<xacro:hole_definition link_name="hole_9" 
						   length="0.01" 
						   radius="0.004"
						   x="${(0.431575 + x_offset)}" y="${-(0.87606 + y_offset)}" z="${(0.045 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>


	<xacro:hole_definition link_name="hole_10" 
						   length="0.01" 
						   radius="0.00275"
						   x="${(0.429349 + x_offset)}" y="${-(0.860216 + y_offset)}" z="${(0.045 + z_offset)}"
						   rx="0" ry="0" rz="0"
						   parent="chair part6.SLDPRT"/>


	<xacro:surface_definition link_name="surface_1"
							  box_x="0.32" box_y="0.001" box_z="0.02"
							  x="${0.369534/2 + x_offset}" y="${-(0.852206/2 + y_offset)}" z="${0.0175 + z_offset}"
							  rx="0" ry="${(-90+84.115)*2*pi/360}" rz="${(3)*2*pi/360}"
							  parent="chair part6.SLDPRT"/>


	<xacro:surface_definition link_name="surface_2"
							  box_x="0.001" box_y="0.017" box_z="0.03"
							  x="${0.354534 + x_offset}" y="${-(0.852206/2 + y_offset)}" z="${0.035 + z_offset}"
							  rx="0" ry="0" rz="0"
							  parent="chair part6.SLDPRT"/>
</robot>